version: '3.8'

services:
  movie-scanner:
    build: .
    expose:
      - "5000"
    volumes:
      - movie_data:/app/instance
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - TMDB_API_KEY=${TMDB_API_KEY:-your_api_key_here}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - movie-scanner
    restart: unless-stopped

volumes:
  movie_data: